services:
  - type: web
    name: nutrition-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn nutrition_prediction_apiV1:app --host 0.0.0.0 --port 10000"
    pythonVersion: 3.10
    envVars:
      - key: GEMINI_API_KEY
        sync: false
